// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 31.03.2026, 21:59:03
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/konrad/repo/OpenFamily/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/konrad/repo/OpenFamily/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/konrad/repo/OpenFamily/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/konrad/repo/OpenFamily/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/konrad/repo/OpenFamily/frontend/plugins/**/*.{js,ts,mjs}","/home/konrad/repo/OpenFamily/frontend/composables/**/*.{js,ts,mjs}","/home/konrad/repo/OpenFamily/frontend/utils/**/*.{js,ts,mjs}","/home/konrad/repo/OpenFamily/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/konrad/repo/OpenFamily/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/konrad/repo/OpenFamily/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/konrad/repo/OpenFamily/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;